
include ../makefiles/platforms.mk
include ../user.mk
include ../makefiles/default.mk


main: $(ILUPACK)

$(DIRILUPACK)*perm*.o: $(DIRILUPACK)scaleprefix.c


$(PRECISION)*.o: ../include/ilupackmacros.h
$(PRECISION)*.o: ../include/ilupack.h
$(PRECISION)*.o: ../include/namesilupack.h
