#ifndef _ILU_PACK_MACROS_H
#define _ILU_PACK_MACROS_H

#ifdef _DOUBLE_REAL_
#define MYDDOTC                       myddot
#define SINGLESYMILUPACKDELETE        ssymamgdelete
#define SINGLESYMILUPACKINFO          ssymamginfo
#define SINGLESYMSPDILUPACKCONVERT    ssymspdamgconvert
#define SINGLESYMILUPACKNNZ           ssymamgnnz
#define SINGLESYMILUPACKSAVEDIAG      sdsymamgsavediag
#define SINGLESYMILUPACKSAVEDIAGGEP   sdsymamgsavediaggep
#define SINGLESYMILUPACKSOL           sdsymamgsol
#define SINGLESYMILUPACKINIT          sdsymamginit
#define SINGLESYMILUPACKRESTOREDIAG   sdsymamgrestorediag
#define SINGLEILUPACKUNDOSCALING      sdamgundoscaling
#define SINGLESYMILUPACKFACTOR        sdsymamgfactor
#define SINGLESYMILUPACKFACTORGEP     sdsymamgfactorgep

#define TRANS                  'T'
#define PJD_EV                 dpjd
#define PJD_GEP                dpjd_gep
#define PJDREVCOM_EV           dpjdrevcom
#define PJDREVCOM_GEP          dpjdrevcom_gep
#define JDREVCOM_EV            djdrevcom
#define JDREVCOM_GEP           djdrevcom_gep
#define PJDCLEANUP_EV          dpjdcleanup
#define PJDCLEANUP_GEP         dpjdcleanup_gep
#define PJDCLEANUP1            dpjdcleanup1
#define PJDRVCOM               dpjdrvcom
#define JDRVCOM                djdrvcom
#define PJDINIT                dpjdinit
#define SHRINK                 dshrink
#define SORTEV                 dsortev
#define STOPTEST               dstoptest
#define REPGS                  drepgs
#define SORTRX                 dsortrx
#define LSOLREVCOM             dlsolrevcom
#define SOLPROJEP              dsolprojep
#define ESTERR                 desterr
#define DGLPRECSETUP           ddglprecsetup       
#define DGLPRECSOL             ddglprecsol         
#define DGLPRECDELETE          ddglprecdelete      
#define SYMILUPACKDELETE       dsymamgdelete
#define SYMILUPACKSOLVER       dsymamgsolver
#define SYMILUPACKNNZ          dsymamgnnz
#define SYMILUPACKSAVEDIAG     dsymamgsavediag
#define SYMILUPACKSAVEDIAGGEP  dsymamgsavediaggep
#define SYMILUPACKRESTOREDIAG  dsymamgrestorediag
#define SYMILUPACKSOL          dsymamgsol
#define SYMILUPACKFACTOR       dsymamgfactor
#define SYMILUPACKFACTORGEP    dsymamgfactorgep
#define SYMILUPACKINIT         dsymamginit
#define SYMILUPACKINFO         dsymamginfo
#define ILUPACKUNDOSCALING     damgundoscaling
#define MATVECA                dmatvec_jada
#define NRM2                   dnrm2
#define LAMCH                  dlamch
#define GEMV                   dgemv
#define SYR0                   dsyr
#define SYR20                  dsyr2
#define SYRK                   dsyrk
#define SYR2K                  dsyr2k
#define SYMV                   dsymv
#define SYEV                   dsyev
#define SYGV                   dsygv
#define GEEV                   dgeev
#define POSV                   dposv
#define LARNV                  dlarnv
#define GEQRF                  dgeqrf
#define GEMM                   dgemm
#define GERK                   dger
#define ORMQR                  dormqr




#define SYMAMGSAVEDIAG    DSYMAMGsavediag
#define SYMAMGSAVEDIAGGEP DSYMAMGsavediaggep
#define SYMAMGRESTOREDIAG DSYMAMGrestorediag
#define ILUPACKINIT dgnlamginit
#define ILUPACKFACTOR dgnlamgfactor
#define ILUPACKSOLVER dgnlamgsolver
#define ILUPACKSOL dgnlamgsol
#define ILUPACKDELETE dgnlamgdelete
#define ILUPACKINFO dgnlamginfo
#define ILUPACKNNZ dgnlamgnnz

#define SPDILUPACKINIT dspdamginit
#define SPDILUPACKFACTOR dspdamgfactor
#define SPDILUPACKSOLVER dspdamgsolver
#define SPDILUPACKSOL dspdamgsol
#define SPDILUPACKDELETE dspdamgdelete
#define SPDILUPACKINFO dspdamginfo
#define SPDILUPACKNNZ dspdamgnnz
#define SYMSPDILUPACKCONVERT dsymspdamgconvert

#define SYMSPDCONVERT DSYMSPDAMGconvert

#define GETEPS        dgeteps
#define MY_OWN_EPS    2.2205d-16
#define MY_OWN_RINF   1.0d300
#define _REAL_MAX_    _D_REAL_MAX_
#define REALS         doubleprecision
#define FLOAT         doubleprecision
#define CSRMAT        Dmat
#define AMGLEVELMAT   DAMGlevelmat
#define ILUPACKPARAM  DILUPACKparam
#define GNLAGGRESSIVEDROPPING DGNLaggressivedropping 
#define SPDAGGRESSIVEDROPPING DSPDaggressivedropping 
#define SPTRF dsptrf
#define SPTRS dsptrs
#define GNLSYMMWM DGNLsmwm

#define ROWSCALE Drowscale
#define COLSCALE Dcolscale
#define SPDSCALE DSPDscale
#define SYMSCALE DSYMscale
#define CNRMS Dcnrms
#define RNRMS Drnrms
#define DIAMUA DDiagMultA
#define AMUDIA DAMultDiag

#define CSRMATVEC DGNLmatvec
#define CSRMATTVEC DGNLmattvec
#define CSRMATHVEC DGNLmathvec
#define SYMMATVEC DSYMmatvec
#define SSMMATVEC DSSMmatvec
#define HERMATVEC DSYMmatvec
#define SETUPGRAPH Dsetupgraph
#define SETUPGRAPH_EPSILON Dsetupgraph_epsilon

#define AMGDELETE DGNLAMGdelete
#define SPDAMGDELETE DSPDAMGdelete

#define AMGSETUP DGNLAMGfactor
#define SPDAMGSETUP DSPDAMGfactor
#define AMGFACTOR DGNLAMGfactor
#define SPDAMGFACTOR DSPDAMGfactor
#define AMGEXTRACT DGNLAMGextract
#define SPDAMGEXTRACT DSYMAMGextract
#define SYMAMGEXTRACT DSYMAMGextract
#define AMGSOL DGNLAMGsol
#define AMGTSOL DGNLAMGtsol
#define AMGDLSOL DGNLAMGdlsol
#define AMGDUSOL DGNLAMGdusol
#define AMGLSOL DGNLAMGlsol
#define AMGUSOL DGNLAMGusol
#define AMGTDLSOL DGNLAMGtdlsol
#define AMGTDUSOL DGNLAMGtdusol
#define AMGTLSOL DGNLAMGtlsol
#define AMGTUSOL DGNLAMGtusol
#define AMGDRIVER DGNLAMGdriver
#define AMGSOLVER DGNLAMGsolver
#define SPDAMGSOLVER DSPDAMGsolver
#define SYMAMGSOLVER DSYMAMGsolver
#define AMGINIT DGNLAMGinit
#define AMGGETPARAMS DGNLAMGgetparams
#define AMGSETPARAMS DGNLAMGsetparams
#define SPDAMGSOL DSPDAMGsol
#define SPDAMGINIT DSPDAMGinit
#define SPDAMGGETPARAMS DSPDAMGgetparams
#define SPDAMGSETPARAMS DSPDAMGsetparams
#define SYMAMGINIT DSYMAMGinit
#define SYMAMGGETPARAMS DSYMAMGgetparams
#define SYMAMGSETPARAMS DSYMAMGsetparams

#define LDLP DSPDldlp
#define LDLPSOL DSPDldlpsol
#define LUPQ DGNLlupq
#define LUPQSOL DGNLlupqsol
#define LUPQLSOL DGNLlupqlsol
#define LUPQUSOL DGNLlupqusol
#define LUPQDLSOL DGNLlupqdlsol
#define LUPQDUSOL DGNLlupqdusol
#define LUPQTSOL DGNLlupqtsol
#define LUPQTLSOL DGNLlupqtlsol
#define LUPQTUSOL DGNLlupqtusol
#define LUPQTDLSOL DGNLlupqtdlsol
#define LUPQTDUSOL DGNLlupqtdusol


#define ILDLC DSYMildlc
#define ILDLCSOL DSYMildlcsol
#define ILUC DGNLiluc
#define PILUC DGNLpiluc
#define SPILUC DGNLspiluc
#define MPILUC DGNLmpiluc
#define PILDLC DSPDpiluc
#define MPILDLC DSPDmpiluc
#define ILUCSOL DGNLilucsol
#define ILUCTSOL DGNLiluctsol
#define ILUCDLSOL DGNLilucdlsol
#define ILUCTDLSOL DGNLiluctdlsol
#define ILUCDUSOL DGNLilucdusol
#define ILUCTDUSOL DGNLiluctdusol
#define ILUCLSOL DGNLiluclsol
#define ILUCTLSOL DGNLiluctlsol
#define ILUCUSOL DGNLilucusol
#define ILUCTUSOL DGNLiluctusol

#define PILUCDLSOL DGNLpilucdlsol
#define PILUCTDLSOL DGNLpiluctdlsol
#define PILUCDUSOL DGNLpilucdusol
#define PILUCTDUSOL DGNLpiluctdusol
#define PILUCLSOL DGNLpiluclsol
#define PILUCTLSOL DGNLpiluctlsol
#define PILUCUSOL DGNLpilucusol
#define PILUCTUSOL DGNLpiluctusol

#define ILUTP DGNLilutp
#define ILUT DGNLilut
#define LUSOL DGNLlusol
#define LUTSOL DGNLlutsol
#define LULSOL DGNLlulsol
#define LUTLSOL DGNLlutlsol
#define LUUSOL DGNLluusol
#define LUTUSOL DGNLlutusol
#define LUDLSOL DGNLludlsol
#define LUTDLSOL DGNLlutdlsol
#define LUDUSOL DGNLludusol
#define LUTDUSOL DGNLlutdusol

#define CPERM Dcperm
#define RPERM Drperm

#define PERMNULL DGNLperm_null
#define PERMND DGNLperm_nd
#define PERMRCM DGNLperm_rcm
#define PERMAMF DGNLperm_amf
#define PERMAMD DGNLperm_amd
#define PERMMMD DGNLperm_mmd
#define PERMMETISE DGNLperm_metis_e
#define PERMMETISN DGNLperm_metis_n
#define PERMPQ DGNLperm_pq
#define PERMFC DGNLperm_fc
#define INDFC Dindfc
#define SYMPERMFC DSYMperm_fc
#define SYMINDFC DSYMindfc
#define SPDPERMFC DSPDperm_fc
#define SPDINDFC DSPDindfc

#define PERMFCV DGNLperm_fcv
#define INDFCV Dindfcv
#define SYMPERMFCV DSYMperm_fcv
#define SYMINDFCV DSYMindfcv
#define SPDPERMFCV DSPDperm_fcv
#define SPDINDFCV DSPDindfcv

#define PERMP DGNLperm_p
#define PERMINDSET DGNLperm_indset

#define SPDPERMNULL DSPDperm_null
#define SPDPERMND DSPDperm_nd
#define SPDPERMRCM DSPDperm_rcm
#define SPDPERMAMF DSPDperm_amf
#define SPDPERMAMD DSPDperm_amd
#define SPDPERMMMD DSPDperm_mmd
#define SPDPERMMETISE DSPDperm_metis_e
#define SPDPERMMETISN DSPDperm_metis_n
#define SPDPERMPP DSPDperm_pp
#define SPDPERMINDSET DSPDperm_indset

#define SYMPERMNULL DSYMperm_null
#define SYMPERMND DSYMperm_nd
#define SYMPERMRCM DSYMperm_rcm
#define SYMPERMAMF DSYMperm_amf
#define SYMPERMAMD DSYMperm_amd
#define SYMPERMMMD DSYMperm_mmd
#define SYMPERMMETISE DSYMperm_metis_e
#define SYMPERMMETISN DSYMperm_metis_n
#define SYMPERMINDSET DSYMperm_indset

#define PERMMWMRCM DGNLperm_mwm_rcm
#define PERMMWMMMD DGNLperm_mwm_mmd
#define PERMMWMAMF DGNLperm_mwm_amf
#define PERMMWMAMD DGNLperm_mwm_amd
#define PERMMWMMETISE DGNLperm_mwm_metis_e
#define PERMMWMMETISN DGNLperm_mwm_metis_n

#define SYMPERMMWMRCM DSYMperm_mwm_rcm
#define SYMPERMMWMMMD DSYMperm_mwm_mmd
#define SYMPERMMWMAMF DSYMperm_mwm_amf
#define SYMPERMMWMAMD DSYMperm_mwm_amd
#define SYMPERMMWMMETISE DSYMperm_mwm_metis_e
#define SYMPERMMWMMETISN DSYMperm_mwm_metis_n

#define PERMMC64RCM DGNLperm_mc64_rcm
#define PERMMC64MMD DGNLperm_mc64_mmd
#define PERMMC64AMF DGNLperm_mc64_amf
#define PERMMC64AMD DGNLperm_mc64_amd
#define PERMMC64METISE DGNLperm_mc64_metis_e
#define PERMMC64METISN DGNLperm_mc64_metis_n

#define SPARTRAN Dspartran
#define QSORT Dqsort
#define QSORT2 Dqsort2
#define QQSORT Dqqsort
#define QQSORT2 Dqqsort2
#define QQSORTS Dqqsorts
#define QQSORTS2 Dqqsorts2
#define QSPLIT Dqsplit
#define QSPLIT2 Dqsplit2
#define QSEPARATE Dqseparate
#define CLEAR Dclear
#define INDSET Dindset
#define PQPERM DPQpermF
#define PPERM DPpermF
#define PPPERM DPPpermF
#define WDIAG DwDiagRF
#define WPDIAG DwPDiagRF
#define QSORTR2I dqsortr2i
#define SWAPM dswapm
#define SPDWDIAG DSPDwDiagRF
#define BISINIT Dbisinit
#define STOPBIS Dstopbis
#define TIDYCG Dtidycg
#define MGSRO Dmgsro
#define GIVENS Dgivens
#define BRKDN Dbrkdn

#define CSRCSC Dcsrcsc
#define CSRCSC2 Dcsrcsc2
#define READMTC Dreadmtc
#define WRITEMTC Dwritemtc
#define READVECTORS Dreadvectors
#define WRITEVECTORS Dwritevectors
#define PCG Dpcg
#define BCG Dbcg
#define SBCG DSYMbcg
#define SQMR DSYMqmr
#define GMRES Dgmres
#define FGMRES Dfgmres

#define DISTDOT ddot
#define DISTDOTU ddot
#define DISTDOT2 ddot2
#define COPY dcopy
#define AXPY daxpy
#define ROTG drotg
#define ROT drot
#define NRM dnrm2
#define I_AMAX idamax
#define ASUM dasum
#define SCAL   dscal
#define RSCAL  dscal

#define MC64I mc64id
#define MC64A mc64ad
#define MC64IR mc64id
#define MC64AR mc64ad

#define FABS(A) (((A)>=0)?(A):(-(A)))
#define RABS(A)     dabs(A)
#define ABS(A) dabs(A)
#define FLOATABS(A) dabs(A)
#define FLOATABSNAME dabs
#define SQRT(A) dsqrt(A)
#define LOG(A) dlog(A)
#define LOG10(A) dlog10(A)
#define IREAL(A) dble(A)
#define ABSFNAME dabs
#define SQRTFNAME dsqrt
#define LOGFNAME dlog
#define LOGTENFNAME dlog10
#define CTOD(A) (A)
#define CONJ(A) (A)
#define FNULL 0.0d0
#define FONE 1.0d0
#define RHALF 0.5d0
#define RONE 1.0d0
#define RTWO 2.0d0
#define RFOUR 4.0d0
#define RZERO 0.0d0
#define REAL_MAX 1.0d300
#define SIGNUM 1.0d0
#define SIGNUM2 1.0d0
#define TWICE 1

#elif defined _SINGLE_REAL_
#define MYDDOTC                 mysdot
#define TRANS                   'T'
#define PJD_EV                  spjd
#define PJD_GEP                 spjd_gep
#define PJDREVCOM_EV            spjdrevcom
#define PJDREVCOM_GEP           spjdrevcom_gep
#define JDREVCOM_EV             sjdrevcom
#define JDREVCOM_GEP            sjdrevcom_gep
#define PJDCLEANUP_EV           spjdcleanup
#define PJDCLEANUP_GEP          spjdcleanup_gep
#define PJDCLEANUP1             spjdcleanup1
#define PJDRVCOM                spjdrvcom
#define JDRVCOM                 sjdrvcom
#define PJDINIT                 spjdinit
#define SHRINK                  sshrink
#define SORTEV                  ssortev
#define STOPTEST                sstoptest
#define REPGS                   srepgs
#define SORTRX                  ssortrx
#define LSOLREVCOM              slsolrevcom
#define SOLPROJEP               ssolprojep
#define ESTERR                  sesterr
#define DGLPRECSETUP            sdglprecsetup       
#define DGLPRECSOL              sdglprecsol         
#define DGLPRECDELETE           sdglprecdelete      
#define SYMILUPACKDELETE        ssymamgdelete
#define SYMILUPACKSOLVER        ssymamgsolver
#define SYMILUPACKNNZ           ssymamgnnz
#define SYMILUPACKSAVEDIAG      ssymamgsavediag
#define SYMILUPACKSAVEDIAGGEP   ssymamgsavediaggep
#define SYMILUPACKRESTOREDIAG   ssymamgrestorediag
#define SYMILUPACKSOL           ssymamgsol
#define SYMILUPACKFACTOR        ssymamgfactor
#define SYMILUPACKFACTORGEP     ssymamgfactorgep
#define SYMILUPACKINIT          ssymamginit
#define SYMILUPACKINFO          ssymamginfo
#define ILUPACKUNDOSCALING      samgundoscaling
#define MATVECA                 smatvec_jada
#define NRM2                    snrm2
#define LAMCH                   slamch
#define GEMV                    sgemv
#define SYR0                    ssyr
#define SYR20                   ssyr2
#define SYRK                    ssyrk
#define SYR2K                   ssyr2k
#define SYMV                    ssymv
#define SYEV                    ssyev
#define SYGV                    ssygv
#define GEEV                    sgeev
#define POSV                    sposv
#define LARNV                   slarnv
#define GEQRF                   sgeqrf
#define GEMM                    sgemm
#define GERK                    sger
#define ORMQR                   sormqr

#define SYMAMGSAVEDIAG        SSYMAMGsavediag
#define SYMAMGSAVEDIAGGEP     SSYMAMGsavediaggep
#define SYMAMGRESTOREDIAG     SSYMAMGrestorediag
#define ILUPACKINIT           sgnlamginit
#define ILUPACKFACTOR         sgnlamgfactor
#define ILUPACKSOLVER         sgnlamgsolver
#define ILUPACKSOL            sgnlamgsol
#define ILUPACKDELETE         sgnlamgdelete
#define ILUPACKINFO           sgnlamginfo
#define ILUPACKNNZ            sgnlamgnnz

#define SPDILUPACKINIT        sspdamginit
#define SPDILUPACKFACTOR      sspdamgfactor
#define SPDILUPACKSOLVER      sspdamgsolver
#define SPDILUPACKSOL         sspdamgsol
#define SPDILUPACKDELETE      sspdamgdelete
#define SPDILUPACKINFO        sspdamginfo
#define SPDILUPACKNNZ         sspdamgnnz
#define SYMSPDILUPACKCONVERT  ssymspdamgconvert

#define SYMSPDCONVERT         SSYMSPDAMGconvert

#define GETEPS                sgeteps
#define MY_OWN_EPS            1.1922e-7
#define MY_OWN_RINF           1.0e30
#define _REAL_MAX_            _S_REAL_MAX_
#define REALS                 real
#define FLOAT                 real
#define CSRMAT                Smat
#define AMGLEVELMAT           SAMGlevelmat
#define ILUPACKPARAM          SILUPACKparam
#define GNLAGGRESSIVEDROPPING SDGNLaggressivedropping 
#define SPDAGGRESSIVEDROPPING SSPDaggressivedropping 
#define SPTRF                 ssptrf
#define SPTRS                 ssptrs
#define GNLSYMMWM             SGNLsmwm

#define ROWSCALE              Srowscale
#define COLSCALE              Scolscale
#define SPDSCALE              SSPDscale
#define SYMSCALE              SSYMscale
#define CNRMS                 Scnrms
#define RNRMS                 Srnrms
#define DIAMUA                SDiagMultA
#define AMUDIA                SAMultDiag

#define CSRMATVEC             SGNLmatvec
#define CSRMATTVEC            SGNLmattvec
#define CSRMATHVEC            SGNLmathvec
#define SYMMATVEC             SSYMmatvec
#define SSMMATVEC             SSSMmatvec
#define HERMATVEC             SSYMmatvec
#define SETUPGRAPH            Ssetupgraph
#define SETUPGRAPH_EPSILON    Ssetupgraph_epsilon

#define AMGDELETE             SGNLAMGdelete
#define SPDAMGDELETE          SSPDAMGdelete

#define AMGSETUP              SGNLAMGfactor
#define SPDAMGSETUP           SSPDAMGfactor
#define AMGFACTOR             SGNLAMGfactor
#define SPDAMGFACTOR          SSPDAMGfactor
#define AMGEXTRACT            SGNLAMGextract
#define SPDAMGEXTRACT         SSYMAMGextract
#define SYMAMGEXTRACT         SSYMAMGextract
#define AMGSOL                SGNLAMGsol
#define AMGTSOL               SGNLAMGtsol
#define AMGDLSOL              SGNLAMGdlsol
#define AMGDUSOL              SGNLAMGdusol
#define AMGLSOL               SGNLAMGlsol
#define AMGUSOL               SGNLAMGusol
#define AMGTDLSOL             SGNLAMGtdlsol
#define AMGTDUSOL             SGNLAMGtdusol
#define AMGTLSOL              SGNLAMGtlsol
#define AMGTUSOL              SGNLAMGtusol
#define AMGDRIVER             SGNLAMGdriver
#define AMGSOLVER             SGNLAMGsolver
#define SPDAMGSOLVER          SSPDAMGsolver
#define SYMAMGSOLVER          SSYMAMGsolver
#define AMGINIT               SGNLAMGinit
#define AMGGETPARAMS          SGNLAMGgetparams
#define AMGSETPARAMS          SGNLAMGsetparams
#define SPDAMGSOL             SSPDAMGsol
#define SPDAMGINIT            SSPDAMGinit
#define SPDAMGGETPARAMS       SSPDAMGgetparams
#define SPDAMGSETPARAMS       SSPDAMGsetparams
#define SYMAMGINIT            SSYMAMGinit
#define SYMAMGGETPARAMS       SSYMAMGgetparams
#define SYMAMGSETPARAMS       SSYMAMGsetparams

#define LDLP                  SSPDldlp
#define LDLPSOL               SSPDldlpsol
#define LUPQ                  SGNLlupq
#define LUPQSOL               SGNLlupqsol
#define LUPQLSOL              SGNLlupqlsol
#define LUPQUSOL              SGNLlupqusol
#define LUPQDLSOL             SGNLlupqdlsol
#define LUPQDUSOL             SGNLlupqdusol
#define LUPQTSOL              SGNLlupqtsol
#define LUPQTLSOL             SGNLlupqtlsol
#define LUPQTUSOL             SGNLlupqtusol
#define LUPQTDLSOL            SGNLlupqtdlsol
#define LUPQTDUSOL            SGNLlupqtdusol


#define ILDLC SSYMildlc
#define ILDLCSOL SSYMildlcsol
#define ILUC SGNLiluc
#define PILUC SGNLpiluc
#define SPILUC SGNLspiluc
#define MPILUC SGNLmpiluc
#define PILDLC SSPDpiluc
#define MPILDLC SSPDmpiluc
#define ILUCSOL SGNLilucsol
#define ILUCTSOL SGNLiluctsol
#define ILUCDLSOL SGNLilucdlsol
#define ILUCTDLSOL SGNLiluctdlsol
#define ILUCDUSOL SGNLilucdusol
#define ILUCTDUSOL SGNLiluctdusol
#define ILUCLSOL SGNLiluclsol
#define ILUCTLSOL SGNLiluctlsol
#define ILUCUSOL SGNLilucusol
#define ILUCTUSOL SGNLiluctusol

#define PILUCDLSOL SGNLpilucdlsol
#define PILUCTDLSOL SGNLpiluctdlsol
#define PILUCDUSOL SGNLpilucdusol
#define PILUCTDUSOL SGNLpiluctdusol
#define PILUCLSOL SGNLpiluclsol
#define PILUCTLSOL SGNLpiluctlsol
#define PILUCUSOL SGNLpilucusol
#define PILUCTUSOL SGNLpiluctusol

#define ILUTP SGNLilutp
#define ILUT SGNLilut
#define LUSOL SGNLlusol
#define LUTSOL SGNLlutsol
#define LULSOL SGNLlulsol
#define LUTLSOL SGNLlutlsol
#define LUUSOL SGNLluusol
#define LUTUSOL SGNLlutusol
#define LUDLSOL SGNLludlsol
#define LUTDLSOL SGNLlutdlsol
#define LUDUSOL SGNLludusol
#define LUTDUSOL SGNLlutdusol

#define CPERM Scperm
#define RPERM Srperm

#define PERMNULL SGNLperm_null
#define PERMND SGNLperm_nd
#define PERMRCM SGNLperm_rcm
#define PERMAMF SGNLperm_amf
#define PERMAMD SGNLperm_amd
#define PERMMMD SGNLperm_mmd
#define PERMMETISE SGNLperm_metis_e
#define PERMMETISN SGNLperm_metis_n
#define PERMPQ SGNLperm_pq
#define PERMFC SGNLperm_fc
#define INDFC Sindfc
#define SYMPERMFC SSYMperm_fc
#define SYMINDFC SSYMindfc
#define SPDPERMFC SSPDperm_fc
#define SPDINDFC SSPDindfc

#define PERMFCV SGNLperm_fcv
#define INDFCV Sindfcv
#define SYMPERMFCV SSYMperm_fcv
#define SYMINDFCV SSYMindfcv
#define SPDPERMFCV SSPDperm_fcv
#define SPDINDFCV SSPDindfcv

#define PERMP SGNLperm_p
#define PERMINDSET SGNLperm_indset

#define SPDPERMNULL SSPDperm_null
#define SPDPERMND SSPDperm_nd
#define SPDPERMRCM SSPDperm_rcm
#define SPDPERMAMF SSPDperm_amf
#define SPDPERMAMD SSPDperm_amd
#define SPDPERMMMD SSPDperm_mmd
#define SPDPERMMETISE SSPDperm_metis_e
#define SPDPERMMETISN SSPDperm_metis_n
#define SPDPERMPP SSPDperm_pp
#define SPDPERMINDSET SSPDperm_indset

#define SYMPERMNULL SSYMperm_null
#define SYMPERMND SSYMperm_nd
#define SYMPERMRCM SSYMperm_rcm
#define SYMPERMAMF SSYMperm_amf
#define SYMPERMAMD SSYMperm_amd
#define SYMPERMMMD SSYMperm_mmd
#define SYMPERMMETISE SSYMperm_metis_e
#define SYMPERMMETISN SSYMperm_metis_n
#define SYMPERMINDSET SSYMperm_indset

#define PERMMWMRCM SGNLperm_mwm_rcm
#define PERMMWMMMD SGNLperm_mwm_mmd
#define PERMMWMAMF SGNLperm_mwm_amf
#define PERMMWMAMD SGNLperm_mwm_amd
#define PERMMWMMETISE SGNLperm_mwm_metis_e
#define PERMMWMMETISN SGNLperm_mwm_metis_n

#define SYMPERMMWMRCM SSYMperm_mwm_rcm
#define SYMPERMMWMMMD SSYMperm_mwm_mmd
#define SYMPERMMWMAMF SSYMperm_mwm_amf
#define SYMPERMMWMAMD SSYMperm_mwm_amd
#define SYMPERMMWMMETISE SSYMperm_mwm_metis_e
#define SYMPERMMWMMETISN SSYMperm_mwm_metis_n

#define PERMMC64RCM SGNLperm_mc64_rcm
#define PERMMC64MMD SGNLperm_mc64_mmd
#define PERMMC64AMF SGNLperm_mc64_amf
#define PERMMC64AMD SGNLperm_mc64_amd
#define PERMMC64METISE SGNLperm_mc64_metis_e
#define PERMMC64METISN SGNLperm_mc64_metis_n

#define SPARTRAN Sspartran
#define QSORT Sqsort
#define QSORT2 Sqsort2
#define QQSORT Sqqsort
#define QQSORT2 Sqqsort2
#define QQSORTS Sqqsorts
#define QQSORTS2 Sqqsorts2
#define QSPLIT Sqsplit
#define QSPLIT2 Sqsplit2
#define QSEPARATE Sqseparate
#define CLEAR Sclear
#define INDSET Sindset
#define PQPERM SPQpermF
#define PPERM SPpermF
#define PPPERM SPPpermF
#define WDIAG SwDiagRF
#define WPDIAG SwPDiagRF
#define QSORTR2I sqsortr2i
#define SWAPM sswapm
#define SPDWDIAG SSPDwDiagRF
#define BISINIT Sbisinit
#define STOPBIS Sstopbis
#define TIDYCG Stidycg
#define MGSRO Smgsro
#define GIVENS Sgivens
#define BRKDN Sbrkdn

#define CSRCSC Scsrcsc
#define CSRCSC2 Scsrcsc2
#define READMTC Sreadmtc
#define WRITEMTC Swritemtc
#define READVECTORS Sreadvectors
#define WRITEVECTORS Swritevectors
#define PCG Spcg
#define BCG Sbcg
#define SBCG SSYMbcg
#define SQMR SSYMqmr
#define GMRES Sgmres
#define FGMRES Sfgmres

#define DISTDOT       sdot
#define DISTDOTU      sdot
#define DISTDOT2      sdot2
#define COPY          scopy
#define AXPY          saxpy
#define ROTG          srotg
#define ROT           srot
#define NRM           snrm2
#define I_AMAX        isamax
#define ASUM          sasum
#define SCAL          sscal
#define RSCAL         sscal

#define MC64I         mc64i
#define MC64A         mc64a
#define MC64IR        mc64i
#define MC64AR        mc64a

#define FABS(A)       (((A)>=0)?(A):(-(A)))
#define RABS(A)       abs(A)
#define ABS(A)        abs(A)
#define FLOATABS(A)   abs(A)
#define FLOATABSNAME  abs
#define SQRT(A)       sqrt(A)
#define LOG(A)        log(A)
#define LOG10(A)      log10(A)
#define IREAL(A)      real(A)
#define ABSFNAME      abs
#define SQRTFNAME     sqrt
#define LOGFNAME      log
#define LOGTENFNAME   log10
#define CTOD(A)       (A)
#define CONJ(A)       (A)
#define FNULL         0.0e0
#define FONE          1.0e0
#define RHALF         0.5e0
#define RONE          1.0e0
#define RTWO          2.0e0
#define RFOUR         4.0e0
#define RZERO         0.0e0
#define REAL_MAX      1.0e38
#define SIGNUM        1.0e0
#define SIGNUM2       1.0e0
#define TWICE         1


#elif defined _SINGLE_COMPLEX_
#define MYDDOTC                 mycdotc
#define TRANS                   'C'
#define PJD_EV                  cpjd
#define PJD_GEP                 cpjd_gep
#define PJDREVCOM_EV            cpjdrevcom
#define PJDREVCOM_GEP           cpjdrevcom_gep
#define JDREVCOM_EV             cjdrevcom
#define JDREVCOM_GEP            cjdrevcom_gep
#define PJDCLEANUP_EV           cpjdcleanup
#define PJDCLEANUP_GEP          cpjdcleanup_gep
#define PJDCLEANUP1             cpjdcleanup1
#define PJDRVCOM                cpjdrvcom
#define JDRVCOM                 cjdrvcom
#define PJDINIT                 cpjdinit
#define SHRINK                  cshrink
#define SORTEV                  csortev
#define STOPTEST                cstoptest
#define REPGS                   crepgs
#define SORTRX                  csortrx
#define LSOLREVCOM              clsolrevcom
#define SOLPROJEP               csolprojep
#define ESTERR                  cesterr
#define DGLPRECSETUP            cdglprecsetup       
#define DGLPRECSOL              cdglprecsol         
#define DGLPRECDELETE           cdglprecdelete      
#define SYMILUPACKDELETE        cheramgdelete
#define SYMILUPACKSOLVER        cheramgsolver
#define SYMILUPACKNNZ           cheramgnnz
#define SYMILUPACKSAVEDIAG      cheramgsavediag
#define SYMILUPACKSAVEDIAGGEP   cheramgsavediaggep
#define SYMILUPACKRESTOREDIAG   cheramgrestorediag
#define SYMILUPACKSOL           cheramgsol
#define SYMILUPACKFACTOR        cheramgfactor
#define SYMILUPACKFACTORGEP     cheramgfactorgep
#define SYMILUPACKINIT          cheramginit
#define SYMILUPACKINFO          cheramginfo
#define ILUPACKUNDOSCALING      camgundoscaling
#define MATVECA                 cmatvec_jada
#define NRM2                    scnrm2
#define LAMCH                   slamch
#define GEMV                    cgemv
#define SYR0                    cher
#define SYR20                   cher2
#define SYRK                    cherk
#define SYR2K                   cher2k
#define SYMV                    chemv
#define SYEV                    cheev
#define SYGV                    chegv
#define GEEV                    cgeev
#define POSV                    cposv
#define LARNV                   clarnv
#define GEQRF                   cgeqrf
#define GEMM                    cgemm
#define GERK                    cgerc
#define ORMQR                   cunmqr

#define SYMAMGSAVEDIAG        CHERAMGsavediag
#define SYMAMGSAVEDIAGGEP     CHERAMGsavediaggep
#define SYMAMGRESTOREDIAG     CHERAMGrestorediag
#define ILUPACKINIT           cgnlamginit
#define ILUPACKFACTOR         cgnlamgfactor
#define ILUPACKSOLVER         cgnlamgsolver
#define ILUPACKSOL            cgnlamgsol
#define ILUPACKDELETE         cgnlamgdelete
#define ILUPACKINFO           cgnlamginfo
#define ILUPACKNNZ            cgnlamgnnz

#define SPDILUPACKINIT        chpdamginit
#define SPDILUPACKFACTOR      chpdamgfactor
#define SPDILUPACKSOLVER      chpdamgsolver
#define SPDILUPACKSOL         chpdamgsol
#define SPDILUPACKDELETE      chpdamgdelete
#define SPDILUPACKINFO        chpdamginfo
#define SPDILUPACKNNZ         chpdamgnnz
#define SYMSPDILUPACKCONVERT  cherhpdamgconvert

#define SYMSPDCONVERT         CHERHPDAMGconvert

#define GETEPS                sgeteps
#define MY_OWN_EPS            1.1922e-7
#define MY_OWN_RINF           1.0e30
#define _REAL_MAX_            _S_REAL_MAX_
#define REALS                 real
#define FLOAT                 complex
#define CSRMAT                Cmat
#define RCSRMAT               Smat
#define AMGLEVELMAT           CAMGlevelmat
#define ILUPACKPARAM          CILUPACKparam
#define GNLAGGRESSIVEDROPPING CDGNLaggressivedropping 
#define SPDAGGRESSIVEDROPPING CHPDaggressivedropping 
#define SPTRF                 csptrf
#define SPTRS                 csptrs
#define GNLSYMMWM             CGNLsmwm

#define ROWSCALE              Crowscale
#define COLSCALE              Ccolscale
#define SPDSCALE              CHPDscale
#define SYMSCALE              CHERscale
#define CNRMS                 Ccnrms
#define RNRMS                 Crnrms
#define DIAMUA                CDiagMultA
#define AMUDIA                CAMultDiag

#define CSRMATVEC             CGNLmatvec
#define CSRMATTVEC            CGNLmattvec
#define CSRMATHVEC            CGNLmathvec
#define SYMMATVEC             CHERmatvec
#define SSMMATVEC             CSSMmatvec
#define HERMATVEC             CHERmatvec
#define SETUPGRAPH            Csetupgraph
#define SETUPGRAPH_EPSILON    Csetupgraph_epsilon

#define AMGDELETE             CGNLAMGdelete
#define SPDAMGDELETE          CHPDAMGdelete

#define AMGSETUP              CGNLAMGfactor
#define SPDAMGSETUP           CHPDAMGfactor
#define AMGFACTOR             CGNLAMGfactor
#define SPDAMGFACTOR          CHPDAMGfactor
#define AMGEXTRACT            CGNLAMGextract
#define SPDAMGEXTRACT         CHERAMGextract
#define SYMAMGEXTRACT         CHERAMGextract
#define AMGSOL                CGNLAMGsol
#define AMGTSOL               CGNLAMGtsol
#define AMGDLSOL              CGNLAMGdlsol
#define AMGDUSOL              CGNLAMGdusol
#define AMGLSOL               CGNLAMGlsol
#define AMGUSOL               CGNLAMGusol
#define AMGTDLSOL             CGNLAMGtdlsol
#define AMGTDUSOL             CGNLAMGtdusol
#define AMGTLSOL              CGNLAMGtlsol
#define AMGTUSOL              CGNLAMGtusol
#define AMGDRIVER             CGNLAMGdriver
#define AMGSOLVER             CGNLAMGsolver
#define SPDAMGSOLVER          CHPDAMGsolver
#define SYMAMGSOLVER          CHERAMGsolver
#define AMGINIT               CGNLAMGinit
#define AMGGETPARAMS          CGNLAMGgetparams
#define AMGSETPARAMS          CGNLAMGsetparams
#define SPDAMGSOL             CHPDAMGsol
#define SPDAMGINIT            CHPDAMGinit
#define SPDAMGGETPARAMS       CHPDAMGgetparams
#define SPDAMGSETPARAMS       CHPDAMGsetparams
#define SYMAMGINIT            CHERAMGinit
#define SYMAMGGETPARAMS       CHERAMGgetparams
#define SYMAMGSETPARAMS       CHERAMGsetparams

#define LDLP                  CHPDldlp
#define LDLPSOL               CHPDldlpsol
#define LUPQ                  CGNLlupq
#define LUPQSOL               CGNLlupqsol
#define LUPQLSOL              CGNLlupqlsol
#define LUPQUSOL              CGNLlupqusol
#define LUPQDLSOL             CGNLlupqdlsol
#define LUPQDUSOL             CGNLlupqdusol
#define LUPQTSOL              CGNLlupqtsol
#define LUPQTLSOL             CGNLlupqtlsol
#define LUPQTUSOL             CGNLlupqtusol
#define LUPQTDLSOL            CGNLlupqtdlsol
#define LUPQTDUSOL            CGNLlupqtdusol


#define ILDLC                 CHERildlc
#define ILDLCSOL              CHERildlcsol
#define ILUC                  CGNLiluc
#define PILUC                 CGNLpiluc
#define SPILUC                CGNLspiluc
#define MPILUC                CGNLmpiluc
#define PILDLC                CHPDpiluc
#define MPILDLC               CHPDmpiluc
#define ILUCSOL               CGNLilucsol
#define ILUCTSOL              CGNLiluctsol
#define ILUCDLSOL             CGNLilucdlsol
#define ILUCTDLSOL            CGNLiluctdlsol
#define ILUCDUSOL             CGNLilucdusol
#define ILUCTDUSOL            CGNLiluctdusol
#define ILUCLSOL              CGNLiluclsol
#define ILUCTLSOL             CGNLiluctlsol
#define ILUCUSOL              CGNLilucusol
#define ILUCTUSOL             CGNLiluctusol

#define PILUCDLSOL            CGNLpilucdlsol
#define PILUCTDLSOL           CGNLpiluctdlsol
#define PILUCDUSOL            CGNLpilucdusol
#define PILUCTDUSOL           CGNLpiluctdusol
#define PILUCLSOL             CGNLpiluclsol
#define PILUCTLSOL            CGNLpiluctlsol
#define PILUCUSOL             CGNLpilucusol
#define PILUCTUSOL            CGNLpiluctusol

#define ILUTP                 CGNLilutp
#define ILUT                  CGNLilut
#define LUSOL                 CGNLlusol
#define LUTSOL                CGNLlutsol
#define LULSOL                CGNLlulsol
#define LUTLSOL               CGNLlutlsol
#define LUUSOL                CGNLluusol
#define LUTUSOL               CGNLlutusol
#define LUDLSOL               CGNLludlsol
#define LUTDLSOL              CGNLlutdlsol
#define LUDUSOL               CGNLludusol
#define LUTDUSOL              CGNLlutdusol

#define CPERM                 Ccperm
#define RPERM                 Crperm

#define PERMNULL              CGNLperm_null
#define PERMND                CGNLperm_nd
#define PERMRCM               CGNLperm_rcm
#define PERMAMF               CGNLperm_amf
#define PERMAMD               CGNLperm_amd
#define PERMMMD               CGNLperm_mmd
#define PERMMETISE            CGNLperm_metis_e
#define PERMMETISN            CGNLperm_metis_n
#define PERMPQ                CGNLperm_pq
#define PERMFC                CGNLperm_fc
#define INDFC                 Cindfc
#define SYMPERMFC             CHERperm_fc
#define SYMINDFC              CHERindfc
#define SPDPERMFC             CHPDperm_fc
#define SPDINDFC              CHPDindfc

#define PERMFCV               CGNLperm_fcv
#define INDFCV                Cindfcv
#define SYMPERMFCV            CHERperm_fcv
#define SYMINDFCV             CHERindfcv
#define SPDPERMFCV            CHPDperm_fcv
#define SPDINDFCV             CHPDindfcv

#define PERMP                 CGNLperm_p
#define PERMINDSET            CGNLperm_indset

#define SPDPERMNULL           CHPDperm_null
#define SPDPERMND             CHPDperm_nd
#define SPDPERMRCM            CHPDperm_rcm
#define SPDPERMAMF            CHPDperm_amf
#define SPDPERMAMD            CHPDperm_amd
#define SPDPERMMMD            CHPDperm_mmd
#define SPDPERMMETISE         CHPDperm_metis_e
#define SPDPERMMETISN         CHPDperm_metis_n
#define SPDPERMPP             CHPDperm_pp
#define SPDPERMINDSET         CHPDperm_indset

#define SYMPERMNULL           CHERperm_null
#define SYMPERMND             CHERperm_nd
#define SYMPERMRCM            CHERperm_rcm
#define SYMPERMAMF            CHERperm_amf
#define SYMPERMAMD            CHERperm_amd
#define SYMPERMMMD            CHERperm_mmd
#define SYMPERMMETISE         CHERperm_metis_e
#define SYMPERMMETISN         CHERperm_metis_n
#define SYMPERMINDSET         CHERperm_indset

#define PERMMWMRCM            CGNLperm_mwm_rcm
#define PERMMWMMMD            CGNLperm_mwm_mmd
#define PERMMWMAMF            CGNLperm_mwm_amf
#define PERMMWMAMD            CGNLperm_mwm_amd
#define PERMMWMMETISE         CGNLperm_mwm_metis_e
#define PERMMWMMETISN         CGNLperm_mwm_metis_n

#define SYMPERMMWMRCM         CHERperm_mwm_rcm
#define SYMPERMMWMMMD         CHERperm_mwm_mmd
#define SYMPERMMWMAMF         CHERperm_mwm_amf
#define SYMPERMMWMAMD         CHERperm_mwm_amd
#define SYMPERMMWMMETISE      CHERperm_mwm_metis_e
#define SYMPERMMWMMETISN      CHERperm_mwm_metis_n

#define PERMMC64RCM           CGNLperm_mc64_rcm
#define PERMMC64MMD           CGNLperm_mc64_mmd
#define PERMMC64AMF           CGNLperm_mc64_amf
#define PERMMC64AMD           CGNLperm_mc64_amd
#define PERMMC64METISE        CGNLperm_mc64_metis_e
#define PERMMC64METISN        CGNLperm_mc64_metis_n

#define SPARTRAN              Cspartran
#define QSORT                 Cqsort
#define QSORT2                Cqsort2
#define QQSORT                Cqqsort
#define QQSORT2               Cqqsort2
#define QQSORTS               Cqqsorts
#define QQSORTS2              Cqqsorts2
#define QSPLIT                Cqsplit
#define QSPLIT2               Cqsplit2
#define QSEPARATE             Cqseparate
#define CLEAR                 Cclear
#define INDSET                Cindset
#define PQPERM                CPQpermF
#define PPERM                 CPpermF
#define PPPERM                CPPpermF
#define WDIAG                 CwDiagRF
#define WPDIAG                CwPDiagRF
#define QSORTR2I              sqsortr2i
#define SWAPM                 sswapm
#define SPDWDIAG              CHPDwDiagRF
#define BISINIT               Cbisinit
#define STOPBIS               Cstopbis
#define TIDYCG                Ctidycg
#define MGSRO                 Cmgsro
#define GIVENS                Cgivens
#define BRKDN                 Cbrkdn

#define CSRCSC                Ccsrcsc
#define CSRCSC2               Ccsrcsc2
#define READMTC               Creadmtc
#define WRITEMTC              Cwritemtc
#define READVECTORS           Creadvectors
#define WRITEVECTORS          Cwritevectors
#define PCG                   Cpcg
#define BCG                   Cbcg
#define SBCG                  CHERbcg
#define SQMR                  CHERqmr
#define GMRES                 Cgmres
#define FGMRES                Cfgmres

#define DISTDOT               cdotc
#define DISTDOTU              cdotu
#define DISTDOT2              cdotc2
#define COPY                  ccopy
#define AXPY                  caxpy
#define ROTG                  crotg
#define ROT                   crot
#define NRM                   scnrm2
#define I_AMAX                icamax
#define ASUM                  scasum
#define SCAL                  cscal
#define RSCAL                 csscal
		         
#define MC64I                 mc64i
#define MC64A                 mc64a
#define MC64IR                mc64i
#define MC64AR                mc64a
		         
#define FABS(A)               sqrt((float)((A).r*(A).r+(A).i*(A).i))
#define RABS(A)               abs(A)
#define ABS(A)                cabs(A)
#define FLOATABS(A)           abs(A)
#define FLOATABSNAME          abs
#define SQRT(A)               sqrt(A)
#define LOG(A)                log(A)
#define LOG10(A)              log10(A)
#define IREAL(A)              real(A)
#define ABSFNAME              cabs
#define SQRTFNAME             sqrt
#define LOGFNAME              log
#define LOGTENFNAME           log10
#define CTOD(A)               real(A)
#define CONJ(A)               conjg(A)
#define FNULL                 cmplx(0.0e0,0.0e0)
#define FONE                  cmplx(1.0e0,0.0e0)
#define RHALF                 0.5e0
#define RONE                  1.0e0
#define RTWO                  2.0e0
#define RFOUR                 4.0e0
#define RZERO                 0.0e0
#define REAL_MAX              1.0e38
#define SIGNUM                signum
#define SIGNUM2               signum2
#define TWICE                 2



#else
#define MYDDOTC                       myzdotc
#define SINGLESYMILUPACKDELETE        cheramgdelete
#define SINGLESYMILUPACKINFO          cheramginfo
#define SINGLESYMSPDILUPACKCONVERT    cherhpdamgconvert
#define SINGLESYMILUPACKNNZ           cheramgnnz
#define SINGLESYMILUPACKSAVEDIAG      czheramgsavediag
#define SINGLESYMILUPACKSAVEDIAGGEP   czheramgsavediaggep
#define SINGLESYMILUPACKSOL           czheramgsol
#define SINGLESYMILUPACKINIT          czheramginit
#define SINGLESYMILUPACKRESTOREDIAG   czheramgrestorediag
#define SINGLEILUPACKUNDOSCALING      czamgundoscaling
#define SINGLESYMILUPACKFACTOR        czheramgfactor
#define SINGLESYMILUPACKFACTORGEP     czheramgfactorgep

#define TRANS                   'C'
#define PJD_EV                  zpjd
#define PJD_GEP                 zpjd_gep
#define PJDREVCOM_EV            zpjdrevcom
#define PJDREVCOM_GEP           zpjdrevcom_gep
#define JDREVCOM_EV             zjdrevcom
#define JDREVCOM_GEP            zjdrevcom_gep
#define PJDCLEANUP_EV           zpjdcleanup
#define PJDCLEANUP_GEP          zpjdcleanup_gep
#define PJDCLEANUP1             zpjdcleanup1
#define PJDRVCOM                zpjdrvcom
#define JDRVCOM                 zjdrvcom
#define PJDINIT                 zpjdinit
#define SHRINK                  zshrink
#define SORTEV                  zsortev
#define STOPTEST                zstoptest
#define REPGS                   zrepgs
#define SORTRX                  zsortrx
#define LSOLREVCOM              zlsolrevcom
#define SOLPROJEP               zsolprojep
#define ESTERR                  zesterr
#define DGLPRECSETUP            zdglprecsetup       
#define DGLPRECSOL              zdglprecsol         
#define DGLPRECDELETE           zdglprecdelete      
#define SYMILUPACKDELETE        zheramgdelete
#define SYMILUPACKSOLVER        zheramgsolver
#define SYMILUPACKNNZ           zheramgnnz
#define SYMILUPACKSAVEDIAG      zheramgsavediag
#define SYMILUPACKSAVEDIAGGEP   zheramgsavediaggep
#define SYMILUPACKRESTOREDIAG   zheramgrestorediag
#define SYMILUPACKSOL           zheramgsol
#define SYMILUPACKFACTOR        zheramgfactor
#define SYMILUPACKFACTORGEP     zheramgfactorgep
#define SYMILUPACKINIT          zheramginit
#define SYMILUPACKINFO          zheramginfo
#define ILUPACKUNDOSCALING      zamgundoscaling
#define MATVECA                 zmatvec_jada
#define NRM2                    dznrm2
#define LAMCH                   dlamch
#define GEMV                    zgemv
#define SYR0                    zher
#define SYR20                   zher2
#define SYRK                    zherk
#define SYR2K                   zher2k
#define SYMV                    zhemv
#define SYEV                    zheev
#define SYGV                    zhegv
#define GEEV                    zgeev
#define POSV                    zposv
#define LARNV                   zlarnv
#define GEQRF                   zgeqrf
#define GEMM                    zgemm
#define GERK                    zgerc
#define ORMQR                   zunmqr

#define SYMAMGSAVEDIAG        ZHERAMGsavediag
#define SYMAMGSAVEDIAGGEP     ZHERAMGsavediaggep
#define SYMAMGRESTOREDIAG     ZHERAMGrestorediag
#define ILUPACKINIT           zgnlamginit
#define ILUPACKFACTOR         zgnlamgfactor
#define ILUPACKSOLVER         zgnlamgsolver
#define ILUPACKSOL            zgnlamgsol
#define ILUPACKDELETE         zgnlamgdelete
#define ILUPACKINFO           zgnlamginfo
#define ILUPACKNNZ            zgnlamgnnz

#define SPDILUPACKINIT        zhpdamginit
#define SPDILUPACKFACTOR      zhpdamgfactor
#define SPDILUPACKSOLVER      zhpdamgsolver
#define SPDILUPACKSOL         zhpdamgsol
#define SPDILUPACKDELETE      zhpdamgdelete
#define SPDILUPACKINFO        zhpdamginfo
#define SPDILUPACKNNZ         zhpdamgnnz
#define SYMSPDILUPACKCONVERT  zherhpdamgconvert

#define SYMSPDCONVERT         ZHERHPDAMGconvert

#define GETEPS                dgeteps
#define MY_OWN_EPS            2.2205d-16
#define MY_OWN_RINF           1.0d300
#define _REAL_MAX_            _D_REAL_MAX_
#define REALS                 doubleprecision
#define FLOAT                 doublecomplex
#define CSRMAT                Zmat
#define RCSRMAT               Dmat
#define AMGLEVELMAT           ZAMGlevelmat
#define ILUPACKPARAM          ZILUPACKparam
#define GNLAGGRESSIVEDROPPING ZDGNLaggressivedropping 
#define SPDAGGRESSIVEDROPPING ZHPDaggressivedropping 
#define SPTRF                 zsptrf
#define SPTRS                 zsptrs
#define GNLSYMMWM             ZGNLsmwm

#define ROWSCALE              Zrowscale
#define COLSCALE              Zcolscale
#define SPDSCALE              ZHPDscale
#define SYMSCALE              ZHERscale
#define CNRMS                 Zcnrms
#define RNRMS                 Zrnrms
#define DIAMUA                ZDiagMultA
#define AMUDIA                ZAMultDiag

#define CSRMATVEC             ZGNLmatvec
#define CSRMATTVEC            ZGNLmattvec
#define CSRMATHVEC            ZGNLmathvec
#define SYMMATVEC             ZHERmatvec
#define SSMMATVEC             ZSSMmatvec
#define HERMATVEC             ZHERmatvec
#define SETUPGRAPH            Zsetupgraph
#define SETUPGRAPH_EPSILON    Zsetupgraph_epsilon

#define AMGDELETE             ZGNLAMGdelete
#define SPDAMGDELETE          ZHPDAMGdelete

#define AMGSETUP              ZGNLAMGfactor
#define SPDAMGSETUP           ZHPDAMGfactor
#define AMGFACTOR             ZGNLAMGfactor
#define SPDAMGFACTOR          ZHPDAMGfactor
#define AMGEXTRACT            ZGNLAMGextract
#define SPDAMGEXTRACT         ZHERAMGextract
#define SYMAMGEXTRACT         ZHERAMGextract
#define AMGSOL                ZGNLAMGsol
#define AMGTSOL               ZGNLAMGtsol
#define AMGDLSOL              ZGNLAMGdlsol
#define AMGDUSOL              ZGNLAMGdusol
#define AMGLSOL               ZGNLAMGlsol
#define AMGUSOL               ZGNLAMGusol
#define AMGTDLSOL             ZGNLAMGtdlsol
#define AMGTDUSOL             ZGNLAMGtdusol
#define AMGTLSOL              ZGNLAMGtlsol
#define AMGTUSOL              ZGNLAMGtusol
#define AMGDRIVER             ZGNLAMGdriver
#define AMGSOLVER             ZGNLAMGsolver
#define SPDAMGSOLVER          ZHPDAMGsolver
#define SYMAMGSOLVER          ZHERAMGsolver
#define AMGINIT               ZGNLAMGinit
#define AMGGETPARAMS          ZGNLAMGgetparams
#define AMGSETPARAMS          ZGNLAMGsetparams
#define SPDAMGSOL             ZHPDAMGsol
#define SPDAMGINIT            ZHPDAMGinit
#define SPDAMGGETPARAMS       ZHPDAMGgetparams
#define SPDAMGSETPARAMS       ZHPDAMGsetparams
#define SYMAMGINIT            ZHERAMGinit
#define SYMAMGGETPARAMS       ZHERAMGgetparams
#define SYMAMGSETPARAMS       ZHERAMGsetparams

#define LDLP                  ZHPDldlp
#define LDLPSOL               ZHPDldlpsol
#define LUPQ                  ZGNLlupq
#define LUPQSOL               ZGNLlupqsol
#define LUPQLSOL              ZGNLlupqlsol
#define LUPQUSOL              ZGNLlupqusol
#define LUPQDLSOL             ZGNLlupqdlsol
#define LUPQDUSOL             ZGNLlupqdusol
#define LUPQTSOL              ZGNLlupqtsol
#define LUPQTLSOL             ZGNLlupqtlsol
#define LUPQTUSOL             ZGNLlupqtusol
#define LUPQTDLSOL            ZGNLlupqtdlsol
#define LUPQTDUSOL            ZGNLlupqtdusol


#define ILDLC                 ZHERildlc
#define ILDLCSOL              ZHERildlcsol
#define ILUC                  ZGNLiluc
#define PILUC                 ZGNLpiluc
#define SPILUC                ZGNLspiluc
#define MPILUC                ZGNLmpiluc
#define PILDLC                ZHPDpiluc
#define MPILDLC               ZHPDmpiluc
#define ILUCSOL               ZGNLilucsol
#define ILUCTSOL              ZGNLiluctsol
#define ILUCDLSOL             ZGNLilucdlsol
#define ILUCTDLSOL            ZGNLiluctdlsol
#define ILUCDUSOL             ZGNLilucdusol
#define ILUCTDUSOL            ZGNLiluctdusol
#define ILUCLSOL              ZGNLiluclsol
#define ILUCTLSOL             ZGNLiluctlsol
#define ILUCUSOL              ZGNLilucusol
#define ILUCTUSOL             ZGNLiluctusol

#define PILUCDLSOL            ZGNLpilucdlsol
#define PILUCTDLSOL           ZGNLpiluctdlsol
#define PILUCDUSOL            ZGNLpilucdusol
#define PILUCTDUSOL           ZGNLpiluctdusol
#define PILUCLSOL             ZGNLpiluclsol
#define PILUCTLSOL            ZGNLpiluctlsol
#define PILUCUSOL             ZGNLpilucusol
#define PILUCTUSOL            ZGNLpiluctusol

#define ILUTP                 ZGNLilutp
#define ILUT                  ZGNLilut
#define LUSOL                 ZGNLlusol
#define LUTSOL                ZGNLlutsol
#define LULSOL                ZGNLlulsol
#define LUTLSOL               ZGNLlutlsol
#define LUUSOL                ZGNLluusol
#define LUTUSOL               ZGNLlutusol
#define LUDLSOL               ZGNLludlsol
#define LUTDLSOL              ZGNLlutdlsol
#define LUDUSOL               ZGNLludusol
#define LUTDUSOL              ZGNLlutdusol

#define CPERM                 Zcperm
#define RPERM                 Zrperm

#define PERMNULL              ZGNLperm_null
#define PERMND                ZGNLperm_nd
#define PERMRCM               ZGNLperm_rcm
#define PERMAMF               ZGNLperm_amf
#define PERMAMD               ZGNLperm_amd
#define PERMMMD               ZGNLperm_mmd
#define PERMMETISE            ZGNLperm_metis_e
#define PERMMETISN            ZGNLperm_metis_n
#define PERMPQ                ZGNLperm_pq
#define PERMFC                ZGNLperm_fc
#define INDFC                 Zindfc
#define SYMPERMFC             ZHERperm_fc
#define SYMINDFC              ZHERindfc
#define SPDPERMFC             ZHPDperm_fc
#define SPDINDFC              ZHPDindfc

#define PERMFCV               ZGNLperm_fcv
#define INDFCV                Zindfcv
#define SYMPERMFCV            ZHERperm_fcv
#define SYMINDFCV             ZHERindfcv
#define SPDPERMFCV            ZHPDperm_fcv
#define SPDINDFCV             ZHPDindfcv

#define PERMP                 ZGNLperm_p
#define PERMINDSET            ZGNLperm_indset

#define SPDPERMNULL           ZHPDperm_null
#define SPDPERMND             ZHPDperm_nd
#define SPDPERMRCM            ZHPDperm_rcm
#define SPDPERMAMF            ZHPDperm_amf
#define SPDPERMAMD            ZHPDperm_amd
#define SPDPERMMMD            ZHPDperm_mmd
#define SPDPERMMETISE         ZHPDperm_metis_e
#define SPDPERMMETISN         ZHPDperm_metis_n
#define SPDPERMPP             ZHPDperm_pp
#define SPDPERMINDSET         ZHPDperm_indset

#define SYMPERMNULL           ZHERperm_null
#define SYMPERMND             ZHERperm_nd
#define SYMPERMRCM            ZHERperm_rcm
#define SYMPERMAMF            ZHERperm_amf
#define SYMPERMAMD            ZHERperm_amd
#define SYMPERMMMD            ZHERperm_mmd
#define SYMPERMMETISE         ZHERperm_metis_e
#define SYMPERMMETISN         ZHERperm_metis_n
#define SYMPERMINDSET         ZHERperm_indset

#define PERMMWMRCM            ZGNLperm_mwm_rcm
#define PERMMWMMMD            ZGNLperm_mwm_mmd
#define PERMMWMAMF            ZGNLperm_mwm_amf
#define PERMMWMAMD            ZGNLperm_mwm_amd
#define PERMMWMMETISE         ZGNLperm_mwm_metis_e
#define PERMMWMMETISN         ZGNLperm_mwm_metis_n

#define SYMPERMMWMRCM         ZHERperm_mwm_rcm
#define SYMPERMMWMMMD         ZHERperm_mwm_mmd
#define SYMPERMMWMAMF         ZHERperm_mwm_amf
#define SYMPERMMWMAMD         ZHERperm_mwm_amd
#define SYMPERMMWMMETISE      ZHERperm_mwm_metis_e
#define SYMPERMMWMMETISN      ZHERperm_mwm_metis_n

#define PERMMC64RCM           ZGNLperm_mc64_rcm
#define PERMMC64MMD           ZGNLperm_mc64_mmd
#define PERMMC64AMF           ZGNLperm_mc64_amf
#define PERMMC64AMD           ZGNLperm_mc64_amd
#define PERMMC64METISE        ZGNLperm_mc64_metis_e
#define PERMMC64METISN        ZGNLperm_mc64_metis_n

#define SPARTRAN              Zspartran
#define QSORT                 Zqsort
#define QSORT2                Zqsort2
#define QQSORT                Zqqsort
#define QQSORT2               Zqqsort2
#define QQSORTS               Zqqsorts
#define QQSORTS2              Zqqsorts2
#define QSPLIT                Zqsplit
#define QSPLIT2               Zqsplit2
#define QSEPARATE             Zqseparate
#define CLEAR                 Zclear
#define INDSET                Zindset
#define PQPERM                ZPQpermF
#define PPERM                 ZPpermF
#define PPPERM                ZPPpermF
#define WDIAG                 ZwDiagRF
#define WPDIAG                ZwPDiagRF
#define QSORTR2I              dqsortr2i
#define SWAPM                 dswapm
#define SPDWDIAG              ZHPDwDiagRF
#define BISINIT               Zbisinit
#define STOPBIS               Zstopbis
#define TIDYCG                Ztidycg
#define MGSRO                 Zmgsro
#define GIVENS                Zgivens
#define BRKDN                 Zbrkdn

#define CSRCSC                Zcsrcsc
#define CSRCSC2               Zcsrcsc2
#define READMTC               Zreadmtc
#define WRITEMTC              Zwritemtc
#define READVECTORS           Zreadvectors
#define WRITEVECTORS          Zwritevectors
#define PCG                   Zpcg
#define BCG                   Zbcg
#define SBCG                  ZHERbcg
#define SQMR                  ZHERqmr
#define GMRES                 Zgmres
#define FGMRES                Zfgmres

#define DISTDOT               zdotc
#define DISTDOTU              zdotu
#define DISTDOT2              zdotc2
#define COPY                  zcopy
#define AXPY                  zaxpy
#define ROTG                  zrotg
#define ROT                   zrot
#define NRM                   dznrm2
#define I_AMAX                izamax
#define ASUM                  dzasum
#define SCAL                  zscal
#define RSCAL                 zdscal
		         
#define MC64I                 mc64iz
#define MC64A                 mc64az
#define MC64IR                mc64id
#define MC64AR                mc64ad
		         
#define FABS(A)               sqrt((double)((A).r*(A).r+(A).i*(A).i))
#define RABS(A)               dabs(A)
#define ABS(A)                cdabs(A)
#define FLOATABS(A)           dabs(A)
#define FLOATABSNAME          dabs
#define SQRT(A)               dsqrt(A)
#define LOG(A)                dlog(A)
#define LOG10(A)              dlog10(A)
#define IREAL(A)              dble(A)
#define ABSFNAME              cdabs
#define SQRTFNAME             dsqrt
#define LOGFNAME              dlog
#define LOGTENFNAME           dlog10
#define CTOD(A)               dreal(A)
#define CONJ(A)               dconjg(A)
#define FNULL                 dcmplx(0.0d0,0.0d0)
#define FONE                  dcmplx(1.0d0,0.0d0)
#define RHALF                 0.5d0
#define RONE                  1.0d0
#define RTWO                  2.0d0
#define RFOUR                 4.0d0
#define RZERO                 0.0d0
#define REAL_MAX              1.0d300
#define SIGNUM                signum
#define SIGNUM2               signum2
#define TWICE                 2


#endif


#define MALLOC         MAlloc
#define REALLOC        ReAlloc
#define MC64THRESHOLD  1.0e-2
#define QQSORTI        qqsorti




#endif
